# Setting host
- hosts: localhost
  gather_facts: false

#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    elk_stack_version: 7.13.0

# Imports
- import_playbook: roles/add_helm_repos.yml
- import_playbook: roles/minikube.yml
- import_playbook: roles/helm_plugins.yml
- import_playbook: roles/kube-prom.yml
- import_playbook: roles/wordpress.yml
- import_playbook: roles/mysql_exporter.yml
- import_playbook: roles/elk.yml
- import_playbook: roles/filebeat.yml
- import_playbook: roles/grafana_fixes.yml
#    - name: Start Minikube tunnel. 
#      command: minikube tunnel
#      become: true
#      async: 2592000
#      poll: 0
