# Setting host
- hosts: localhost
  gather_facts: false

#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    custom_namespace: monitoring

  tasks:
#Install kube-prom-stack
    - name: Install K8s Prometheus chart
      kubernetes.core.helm:
        name: kube-prometheus
        release_namespace: '{{ custom_namespace }}'
        create_namespace: true
        chart_ref: prometheus-community/kube-prometheus-stack
        wait: true
        values_files:
          - ../values/kube-prometheus_values.yaml
# Create loadbalancers
    - name: Create a LB for Grafana
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kube-prometheus-grafana
            namespace: '{{ custom_namespace }}'
          spec:
            type: LoadBalancer
            ports:
            - port: 80
              targetPort: 3000
    - name: Create a LB for Prometheus
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kube-prometheus-kube-prome-prometheus
            namespace: '{{ custom_namespace }}'
          spec:
            type: LoadBalancer
            ports:
              - port: 9090
                targetPort: 9090

#Add extra dashboards
    - name: Configmap with Apache Grafana dashboard
      community.kubernetes.k8s:
        state: present
        src: ../deployments/wordpress_apache_dashboard_configmap.yml
    - name: Configmap with Mysql/Mariadb Grafana dashboard
      community.kubernetes.k8s:
        state: present
        src: ../deployments/wordpress_mariadb_dashboard_configmap.yml