# Setting host
- hosts: localhost
  gather_facts: false

#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    custom_namespace: monitoring

  tasks:
#Install kube-prom-stack
    - name: Install K8s Prometheus chart
      kubernetes.core.helm:
        name: kube-prometheus
        release_namespace: '{{ custom_namespace }}'
        create_namespace: true
        chart_ref: prometheus-community/kube-prometheus-stack
        wait: true
        values_files:
          - ../values/kube-prometheus_values.yaml